In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


##### basic methods

In [6]:
print(a.size)  #### to print the number of elements in array

6


In [8]:
print(a.ndim)  #### to print the dimension of the aaray

1


In [11]:
print(a.shape) ### to print the shape of the array the number of elements along each dimension.

(6,)


In [13]:
print(a.dtype)  ### print the data type of the elements of the array

int64


## How to create a basic array

In [14]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [15]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [16]:
print(np.empty(6))

[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.24610723e-306
 1.89146896e-307 7.56571288e-307]


In [17]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [24]:
print(np.linspace(0,100,21))

[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]


In [26]:
x = np.ones(2, dtype=np.int64)  ## specifying data type
x

array([1, 1])

In [31]:
A = np.array([[1,1],
             [0,1]])
B = np.array([[2,0],
             [3,4]])

print(A*B)
print(A@B)
A.dot(B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


array([[5, 4],
       [3, 4]])

In [40]:
rg = np.random.default_rng(1)
print(rg)
a = np.ones((2,3),dtype = int)
print(a)

Generator(PCG64)
[[1 1 1]
 [1 1 1]]


In [43]:
b = rg.random((2,3))
b += a
print(b)


[[1.32973172 1.7884287  1.30319483]
 [1.45349789 1.1340417  1.40311299]]


## slicing

In [44]:
A = np.array([1,2,4,4,5,7])
A

array([1, 2, 4, 4, 5, 7])

In [45]:
print(A[::-1])

[7 5 4 4 2 1]


In [48]:
print(A[1:])

[2 4 4 5 7]


## Multidimensional Array

In [51]:
def f(x,y):
    return 10*x+y

arr = np.fromfunction(f,(5,4),dtype = int)

In [52]:
print(arr)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [56]:
a=np.array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [57]:
a.ravel()  # returns the array, flattened
a

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [58]:
a.reshape(6, 2)  # returns the array with a modified shape

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [59]:
a.T  # returns the array, transposed

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [60]:
a.T.shape
a.shape

(12,)

### No copy at all

In [62]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object

True

In [64]:
def f(x):
    print(id(x))

print(id(a))
f(a)

2023523203088
2023523203088


In [65]:
def f(x):
    print(id(x))
a = (2,4)
print(id(a))
f(a)

2023522644032
2023522644032


In [66]:
def f(x):
    print("Before:", id(x))
    x.append(5)
    print("After:", id(x))

a = [1, 2]
print("Original ID:", id(a))
f(a)
print("After Call:", a)

Original ID: 2023522853952
Before: 2023522853952
After: 2023522853952
After Call: [1, 2, 5]


In [67]:
def f(x):
    print("Before:", id(x))
    x = x + (6,)  # Creates a new tuple!
    print("After:", id(x))

a = (1, 2)
print("Original ID:", id(a))
f(a)
print("After Call:", a)

Original ID: 2023522730176
Before: 2023522730176
After: 2023522639616
After Call: (1, 2)


In [ ]:
a