In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


##### basic methods

In [6]:
print(a.size)  #### to print the number of elements in array

6


In [8]:
print(a.ndim)  #### to print the dimension of the aaray

1


In [11]:
print(a.shape) ### to print the shape of the array the number of elements along each dimension.

(6,)


In [13]:
print(a.dtype)  ### print the data type of the elements of the array

int64


## How to create a basic array

In [14]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [15]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [16]:
print(np.empty(6))

[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.24610723e-306
 1.89146896e-307 7.56571288e-307]


In [17]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [24]:
print(np.linspace(0,100,21))

[  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]
